### PR TITLE
full_card.pdf: Change coala-analyzer.org

### PR DESCRIPTION
**Pull request by kiy4h**
Closes https://github.com/coala/artwork/issues/43

### CODE REVIEW

**Review by srivama — CHANGES_REQUESTED** [review]
Please change http://coala.io/ to https://coala.io/

**Review by ayan-b — APPROVED** [review]

**Review by srivama — APPROVED** [review]

**Comment by jayvdb** [comment]
ack https://github.com/coala/artwork/pull/67/commits/7e33956170d231d267b15231d745a352011a0168

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Comment by jayvdb** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being fastforwarded automatically. Please **DO NOT** push while fastforward is in progress or your changes would be lost permanently :warning:

**Comment by jayvdb** [comment]
Automated fastforward with [GitMate.io](https://gitmate.io) was successful! :tada:

**Pull request merged**
