### PR TITLE
Add ESLintBearLogo.svg

### PR DESCRIPTION
**Pull request by kiy4h**
Added ESLintBearLogo.svg in /artwork/logo/bears/

Related to https://github.com/coala/artwork/issues/21

### CODE REVIEW

**Review by srivama — COMMENTED** [review]
Can you move the ESL logo on the SE corner, that might look better ;)

**Comment by kiy4h** [comment]
@srivama I tried putting the ESLint logo in all corners and here's the result:

img

I think I like the bottom left one the best, what do you think?

**Comment by kiy4h** [comment]
Or, if you think the ESL logo is too big, I resized it to 1/4 of coala logo's width:

whichlogoisbestsmaller

But I think they're too small for some reason, or maybe that's just my design taste ;)

**Comment by srivama** [comment]
You're right. Bottom left 1/3rd looks good :)

**Review by srivama — APPROVED** [review]

**Review by sangamcse — APPROVED** [review]

**Comment by sangamcse** [comment]
ack 59107063516553420d848c2e500ef2879456949a

**Comment by sangamcse** [comment]
@gitmate-bot ff

**Comment by jayvdb** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being fastforwarded automatically. Please **DO NOT** push while fastforward is in progress or your changes would be lost permanently :warning:

**Comment by jayvdb** [comment]
Automated fastforward with [GitMate.io](https://gitmate.io) was successful! :tada:

**Pull request merged**
