### PR TITLE
Added ascii art for all releases

### LINKED ISSUE #45: Archive old release asciiart
Each release of coala included an ascii-art , usually put into the release notes for the release.

Here is the one for release 0.2

https://github.com/coala/artwork/blob/master/artwork/deprecated_artwork/0_2_coala_wombat.txt

We need all of the old ascii-art put into this repository in that folder as an archive.

### PR DESCRIPTION
**Pull request by W3D3**
This pull request includes the ascii art for releases 0.4 to 0.11.

This fixes #45 .

### CODE REVIEW

**Review by ayan-b — COMMENTED** [review]
Hello there @W3D3 ! Good job, but here are some points you may have missed -
Your commit message does not follow the coala guidelines. Please see: https://coala.io/commit
Precisely, you should add a tag, something like `artwork` as mentioned in that link, your commit message should contain sentences in the imperative present tense only, _i.e._ no `Added` but `Add`. Also it should give a brief description on what you have worked upon. And at last fixes/closes issue link.

And only do what is mentioned in the issue, _i.e._, do not change the file name, as it is not mentioned, this helps the reviewers to review easily and thus creating high chances of getting your PR merged. :tada:

And finally squash all the commits into one. Also, your branch is out of date with the master branch, so you need to rebase your commits. Read: https://coala.io/rebase .

All the best, hope to see a lot of contributions from you! :smiley:

**Comment by adtac** [comment]
Just commenting on the artwork: good stuff, I remember having a lot of fun deciding on which release to go with (I released 0.8 and made that artwork on with the help of GIMP and an ASCII art generator! :)).

And yeah, you should probably redo those commit messages.

BTW, you don't need to have a separate commit for each imported version artwork (it looks like you partially followed that principle and then didn't).

**Comment by W3D3** [comment]
@ayan-b Thanks for the heads up. Maybe consider adding a `CONTRIBUTING.md` and/or a `PULL_REQUEST_TEMPLATE.md` to this repo as well so it's clear which contribution guidelines are in place.

> And yeah, you should probably redo those commit messages.
>
> BTW, you don't need to have a separate commit for each imported version artwork (it looks like you partially followed that principle and then didn't).

Yeah i thought GitHub offers that feature where you can squash them and replace them with the pull request body online, but I was wrong. 🤔 
Already fixed this messy pile of commits.

**Comment by adtac** [comment]
I strongly recommend against using any web interface from Github to modify any PR. We only use Github to store/view code, and do merges.

**Review by jayvdb — APPROVED** [review]

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by jayvdb** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by jayvdb** [comment]
ack https://github.com/coala/artwork/pull/52/commits/c1e1afe02bf52967dc78988cea26a40540e5cad7

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Comment by jayvdb** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being fastforwarded automatically. Please **DO NOT** push while fastforward is in progress or your changes would be lost permanently :warning:

**Comment by jayvdb** [comment]
Automated fastforward with [GitMate.io](https://gitmate.io) was successful! :tada:

**Pull request merged**
