### PR TITLE
Change 55+ to 70+

### LINKED ISSUE #50: Change no of languages to 70+ at artwork/ads/basic.ai.svg
A GCI task.

### PR DESCRIPTION
**Pull request by Sheshank-s**
Closes https://github.com/coala/artwork/issues/50

### CODE REVIEW

**Comment by Sheshank-s** [comment]
I guess that didn't work, not sure why there is a new line at the end of the file. Hope that is fine.

**Comment by sangamcse** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by jayvdb** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by sangamcse** [comment]
ack e0c101e048123b375d227b1fbd5372fbe66e9fc8

**Review by sangamcse — DISMISSED** [review]

**Comment by sangamcse** [comment]
@gitmate-bot ff

**Comment by jayvdb** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being fastforwarded automatically. Please **DO NOT** push while fastforward is in progress or your changes would be lost permanently :warning:

**Comment by jayvdb** [comment]
Automated fastforward failed! Please fastforward your pull request manually via the command line.

Reason:
```
Command: git push upstream HEAD:master

Exit Code: 1

Cause:

remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: Required status check "review/gitmate/manual/pr" is pending.        
To <hidden_oauth_token>
 ! [remote rejected] HEAD -> master (protected branch hook declined)
error: failed to push some refs to '<hidden_oauth_token>'


```

**Comment by sangamcse** [comment]
ack e0c101e048123b375d227b1fbd5372fbe66e9fc8

**Comment by jayvdb** [comment]
ack e0c101e

**Comment by jayvdb** [comment]
ack e0c101e

**Comment by sangamcse** [comment]
ack e0c101e048123b375d227b1fbd5372fbe66e9fc8

**Comment by sangamcse** [comment]
@gitmate-bot ff

**Comment by jayvdb** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being fastforwarded automatically. Please **DO NOT** push while fastforward is in progress or your changes would be lost permanently :warning:

**Review by sangamcse — APPROVED** [review]

**Comment by jayvdb** [comment]
Automated fastforward with [GitMate.io](https://gitmate.io) was successful! :tada:

**Pull request merged**
