### PR TITLE
Update gitter link at README : coala-analyzer --> coala

### PR DESCRIPTION
**Pull request by abhayKashyap03**

### CODE REVIEW

**Review by gaocegege — APPROVED** [review]
ack 7d82d28

**Review by jayvdb — APPROVED** [review]

**Comment by jayvdb** [comment]
ack 7d82d28

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Comment by jayvdb** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being fastforwarded automatically. Please **DO NOT** push while fastforward is in progress or your changes would be lost permanently :warning:

**Comment by jayvdb** [comment]
Automated fastforward with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by abhayKashyap03** [comment]
Thank you 👍 :)

**Pull request merged**
