### PR TITLE
coala_color_svg: Add viewbox attribute

### PR DESCRIPTION
**Pull request by Utkarsh1308**
Fixes https://github.com/coala/artwork/issues/34

### CODE REVIEW

**Review by yashovardhan — CHANGES_REQUESTED** [review]
changes are fine
your commit doesn't follow the guidelines, have a look
`Added` is not accepted (its past tense you see 😛 )

**Comment by Utkarsh1308** [comment]
I totally forgot about the past tense sorry for that. Fixed it! Won't happen again

**Review by srivama — CHANGES_REQUESTED** [review]
You aren't fixing a bug. IMO you should use `closes` instead of `fixes` :smile:

**Review by jayvdb — APPROVED** [review]

**Comment by jayvdb** [comment]
ack https://github.com/coala/artwork/pull/41/commits/1ebc20933322d64d1e97099457436c520f16fae4

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Comment by jayvdb** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being fastforwarded automatically. Please **DO NOT** push while fastforward is in progress or your changes would be lost permanently :warning:

**Comment by jayvdb** [comment]
Automated fastforward with [GitMate.io](https://gitmate.io) was successful! :tada:

**Pull request merged**
