### PR TITLE
Add coala 404 page design

### PR DESCRIPTION
**Pull request by Sheshank-s**
Adds a 404 page design for coala.

### CODE REVIEW

**Review by sangamcse — APPROVED** [review]

**Comment by sangamcse** [comment]
ack 1f2e46f0d1c6e69b43e2f2cc4cf51e60db1f2716

**Comment by sangamcse** [comment]
@gitmate-bot ff

**Comment by jayvdb** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being fastforwarded automatically. Please **DO NOT** push while fastforward is in progress or your changes would be lost permanently :warning:

**Comment by jayvdb** [comment]
Automated fastforward with [GitMate.io](https://gitmate.io) was successful! :tada:

**Pull request merged**
