### PR TITLE
coala-header.svg: Add SVG version

### PR DESCRIPTION
**Pull request by sangamcse**
The SVG version of coala-header.png.

Closes https://github.com/coala/artwork/issues/39

### CODE REVIEW

**Comment by sangamcse** [comment]
@jayvdb, the label shows status/STALE but this needs a review. Have a look. Thanks 😃

**Comment by sangamcse** [comment]
Ping @jayvdb

**Review by jayvdb — APPROVED** [review]

**Comment by jayvdb** [comment]
ack https://github.com/coala/artwork/pull/40/commits/61c3fe2100131a7a5f9d15206755b604a2c6a562

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by jayvdb** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Comment by jayvdb** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being fastforwarded automatically. Please **DO NOT** push while fastforward is in progress or your changes would be lost permanently :warning:

**Comment by jayvdb** [comment]
Automated fastforward with [GitMate.io](https://gitmate.io) was successful! :tada:

**Pull request merged**
