### PR TITLE
Add coala-header.png

### PR DESCRIPTION
**Pull request by jayvdb**
Imported from https://github.com/coala/documentation/commit/a6661783c9b18595a5e5886c220dd4e036c3cdf6

Related to https://github.com/coala/artwork/issues/35

### CODE REVIEW

**Comment by hemangsk** [comment]
ack 91a3ea1

**Review by hemangsk — APPROVED** [review]

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Comment by jayvdb** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being fastforwarded automatically. Please **DO NOT** push while fastforward is in progress or your changes would be lost permanently :warning:

**Comment by jayvdb** [comment]
Automated fastforward with [GitMate.io](https://gitmate.io) was successful! :tada:

**Pull request merged**
