### PR TITLE
popup_display: Fix rendering issue

### LINKED ISSUE #51: SVG rendering issue at artwork/popup_display/coala_stand_popup_display_horizontal.svg
Not properly rendering on Firefox and Falkon, not centred on Chrome.
A GCI task.

### PR DESCRIPTION
**Pull request by kiy4h**
There was an SVG rendering issue at
`artwork/popup_display/coala_stand_popup_display_horizontal.svg`.

I fixed it by opening the `.ai` file in Inkscape, changed the "coala.io"
text's color, and replaced the coala logo to
`artwork/logo/coala-color.svg`.

Closes https://github.com/coala/artwork/issues/51

### CODE REVIEW

**Review by srivama — CHANGES_REQUESTED** [review]
Nice work there @Kiy4h. It is rendering well on Chrome and Firefox now. You still need to centre the art though :) It's drifting towards the left.

**Comment by kiy4h** [comment]
Hello @srivama , I don't understand what you mean by "drifting towards the left". Can you show me a screenshot or something?

**Comment by srivama** [comment]
capture
See, the whitespace on the left should match with the whitespace on the right. All the content of the artwork should be centre aligned. It's more visible in the logo, but on looking closely, you can notice a small drift in the line "Linting and Fixing" and the logos below as well.

**Comment by kiy4h** [comment]
@srivama Thanks for pointing that out! It's probably fixed now.

**Review by srivama — DISMISSED** [review]
Nice work! Looks fine now 😄

**Review by sangamcse — CHANGES_REQUESTED** [review]
~`coala.io` font is Roboto:light but in the changes, it is Roboto:Regular. Please fix it to Roboto light.~

Edit:
`coala.io` font is Roboto:Thin but in the changes, it is Roboto:Regular. Please fix it to Roboto Thin.

**Comment by kiy4h** [comment]
@sangamcse Fixed

**Review by sangamcse — CHANGES_REQUESTED** [review]
One correction in my last review, `coala.io` text should be [`Roboto Thin 100`](https://fonts.google.com/specimen/Roboto?selection.family=Roboto:100).

**Comment by kiy4h** [comment]
@sangamcse Alright, I hope I fixed that mistake in my latest commit

**Review by sangamcse — CHANGES_REQUESTED** [review]
You are using Roboto light 300. Please make it to Roboto Thin 100.
Or you can import https://github.com/coala/artwork/blob/master/artwork/logo/coala_text.svg in this SVG.

**Comment by kiy4h** [comment]
@sangamcse I imported the svg, and now the text is not "text" (you can't edit it), it's a path. Is that a problem?

**Comment by sangamcse** [comment]
> @sangamcse I imported the svg, and now the text is not "text" (you can't edit it), it's a path. Is that a problem?

Not a problem. `coala.io` font is fixed throughout all the repository so we don't need to edit those text.

**Review by sangamcse — APPROVED** [review]

**Comment by sangamcse** [comment]
ack f3606b88c73854b17a6e02c2b5239b043d37ab17

**Comment by sangamcse** [comment]
@gitmate-bot ff

**Comment by jayvdb** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being fastforwarded automatically. Please **DO NOT** push while fastforward is in progress or your changes would be lost permanently :warning:

**Comment by jayvdb** [comment]
Automated fastforward with [GitMate.io](https://gitmate.io) was successful! :tada:

**Pull request merged**
